spring:
  profiles: prod
  datasource:
    dynamic:  
      datasource:
        master:
          username: root
          password: root
          
server:
  port: 8088
  address: 0.0.0.0
  
app:
  mysql-host: localhost:33066
  city-data-file: /cities500.txt